### ISSUE TITLE
this vin number is not valid but it is valid?

### ISSUE THREAD

**Issue by lidyum** [idlesign/vininfo#11]
W1V44770513858498

Manufacturer: Mercedes-Benz
Model: 911

**Comment by idlesign** [comment]
`verify_checksum()` method descritpion says: _Not every manufacturer uses VIN checksum rules._
For example check digit is compulsory for Nort America and China but not for Europe.

**Comment by idlesign** [comment]
I've update WMI database in `master` so now `Mercedes-Benz` should be detected correcly for this and similar numbers.

**Comment by lidyum** [comment]
tnhx. But version number is still 1.5.1?

**Comment by idlesign** [comment]
New version 1.6.0 is now available on PyPI. Cheers.

Closing this one. 
Feel free to reopen if the issue is relevant for the latest version.
