### ISSUE TITLE
Vin Checksum returns incorrect results

### ISSUE THREAD

**Issue by ForkrulAssail** [idlesign/vininfo#19]
Numbers from official Russian CTC
WBA71DC010CH14720 -> Reported as incorrect

https://vpic.nhtsa.dot.gov/decoder/CheckDigit/Index/5yj3e1eaxhf000316 -> Reports incorrect 10th digit (zero)
https://www.cjponyparts.com/resources/check-digit-calculator -> Returns correct.

I have read the comment, that not all follow control digit logic, but looks like on some online resources VIN is validated correctly. 

ver. 1.6.0

**Comment by jaimecosme** [comment]
Hi,
I think there is a slight confusion:
9th digit --> Checksum
10th digit --> Model Year (only in USA)

NHTSA is complaining about the model year, because your provided year (0) does not comply with the US allowed characters. It is not complaining about checksum.

You can take a look here:
https://en.m.wikibooks.org/wiki/Vehicle_Identification_Numbers_(VIN_codes)/Model_year

**Comment by ForkrulAssail** [comment]
> Hi, I think there is a slight confusion: 9th digit --> Checksum 10th digit --> Model Year (only in USA)
> 
> NHTSA is complaining about the model year, because your provided year (0) does not comply with US allowed characters. It is not complaining about checksum.
> 
> You can take a look here: https://en.m.wikibooks.org/wiki/Vehicle_Identification_Numbers_(VIN_codes)/Model_year

Does this mean that vininfo work only on US data?
Vin('WBA71DC010CH14720').verify_checksum()  #False

**Comment by jaimecosme** [comment]
Browsing the code, verify_checksum() checks that the 10th char  is not an U, Z or 0 char.
You could comment out those two lines if needed

**Comment by ForkrulAssail** [comment]
> 

So this means that the solution is tailored for US. Just clarifying.

**Comment by jaimecosme** [comment]
I am not a contributor to the repo, but the solution is expecting a rightly encoded model year.

Anyway, it shouldn't be hard to tweak to meet your needs and ignore model year.

**Comment by idlesign** [comment]
Sorry for the delay.

> I have read the comment, that not all follow control digit logic, but looks like on some online resources VIN is validated correctly.

That's probably because we check also a model year.
In new 1.7.0 I've made this check optional so you may want to try 
```
Vin('WBA71DC010CH14720').verify_checksum(check_year=False)
```

Considered closed. 
Feel free to reopen if required.
