### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by slothyrulez** [idlesign/vininfo#2]
Hi, i'm getting this error on some vin's

```
In [1]: import vininfo

In [2]: vininfo.Vin("2LNBL8EV9AX604020")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-267facbdc2ff> in <module>
----> 1 vininfo.Vin("2LNBL8EV9AX604020")

/usr/lib/python3.6/site-packages/vininfo/toolbox.py in __init__(self, num)
     28         self.num = self.validate(num)
     29 
---> 30         details_extractor = self.brand.extractor
     31 
     32         if details_extractor:

AttributeError: 'NoneType' object has no attribute 'extractor'
```

... Some more failing ...
2LMHJ5NK8EBL51686
5J8YD4H5XKL000637
19XFC2F74GE219952
2LNBL8CV9AX610404
58ABK1GG9HU067426
3CZRM3H59CG705077
2LNHM82V09X602289
2LMHJ5NKXEBL54766
2HNYD2H34CH544142
2C4RDGCG3HR589219
2HNYD2H69BH528012
2HNYD28218H504518
2HNYD28378H536818
19XFC1F76GE220868
2LNBL8CV1BX754840
2C4RDGCG6DR590925
2C4RDGCG3HR857170
2C4RDGBG1CR392642
2A4RR5D13AR299997
2LMHJ5NK4EBL51281
2HNYD2H36CH513331
2LMHJ5AR1ABJ50404
2LNBL8EV4BX754439
2LMDJ8JK9FBL32362

**Comment by idlesign** [comment]
`2LNBL8EV9AX604020` seems to be a Lincoln, but there's no info for it in our WMI data base (https://github.com/idlesign/vininfo/blob/master/vininfo/dicts/wmi.py), and additional information extraction for that brand is not implemented.

I've made some changes so that `vininfo` can extract basic info even in such cases and released version 1.1. Check it out.

If you have reliable information about WMI's, pull requests are welcome.

**Comment by slothyrulez** [comment]
Hi @idlesign 

Actually, I don't have a deep knowledge of the VIN standard. My use case was checking validity and performing the checksum on vins before sending them to this API https://vpic.nhtsa.dot.gov/
Before using your lib I found  this other lib that also has some maps on the WMI https://github.com/h3/python-libvin/blob/master/libvin/static.py

**Comment by idlesign** [comment]
> Before using your lib I found this other lib that also has some maps on the WMI 

Thank you. I'll check the sources you've mentioned and maybe integrate some of them.
